version: '3'

services:
  frontend:
    build: ./frontend
    entrypoint: .docker/entrypoint.sh
    ports:
      - 3001:3000
    volumes:
      - ./frontend:/home/node/frontend

  nest_api:
    build: ./nest-api
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - ./nest-api:/home/node/nest_api
